
<header>
    <h1 class="error">404</h1>
    <p class="text-center">Página não encontrada</p>
</header>
<p class="text-center">Não foi possível encontrar a página solicitada.</p>
<div class="row">
    <div class="col-md-6">
        <a class="btn btn-info btn-block btn-3d" href="/index">Voltar ao início</a>
    </div>
    <div class="col-md-6">
        <button class="btn btn-success btn-block btn-3d" onclick="history.back();">Página anterior</button>
    </div>
</div>